parameters:
  - name: appName
    type: string
  - name: imageName
    type: string
  - name: registryUrl
    type: string
    default: "registry.ramongomessilva.com.br"
  - name: envLabel
    type: string
    default: ""

stages:
  - stage: Build
    displayName: "Build Docker Image"
    jobs:
      - job: BuildJob
        displayName: "Build"
        timeoutInMinutes: 20
        steps:
          - checkout: self
            displayName: "Checkout source code"

          - template: notify-start.yml
            parameters:
              appName: ${{ parameters.appName }}
              envLabel: ${{ parameters.envLabel }}

          - template: build-docker.yml
            parameters:
              imageName: ${{ parameters.imageName }}
              registryUrl: ${{ parameters.registryUrl }}
